# theme.toml
name = "Raptor"
license = "MIT"
licenselink = "https://github.com/techquila/hugo-raptor/blob/master/LICENSE"
description = "A modern responsive theme for sites made with the hugo static site generator"
homepage = "https://sod.oscarfono.com/work/go-raptor/"
tags = ["hugo", "golang", "sass", "scss", "responsive", "minimal", "coder", "blogger", "portfolio"]
features = []
min_version = "0.54.0"

[author]
  name = "Sod Oscarfono"
  homepage = "https://sod.oscarfono.com"

# If porting an existing theme
[original]
  name = "Osprey"
  homepage = "https://github.com/tomanistor/osprey"
  repo = "https://github.com/tomanistor/osprey.git"
