version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest

    working_directory: ~/hugo

    environment:
      HUGO_BUILD_DIR: ~/hugo/public

    steps:
      - run: apk update && apk add git
      - checkout
      - run: git submodule sync && git submodule update --init
      - run: echo 'theme = "raptor"' >> config.toml
